language: go
sudo: false

go:
    - 1.6
    - 1.7

install:
    - go get -u golang.org/x/lint/golint
    - go get -u github.com/GeertJohan/fgt

script:
    - make && make check
    - fgt gofmt -l $(find src -name \*.go)
    - fgt find src -type d -exec golint {} \;
